# Generated by Django 6.0.5 on 2026-05-26 19:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='fathers_name',
        ),
        migrations.RemoveField(
            model_name='student',
            name='mothers_name',
        ),
    ]
