# Generated by Django 6.0.5 on 2026-05-26 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0001_initial'),
        ('enrollments', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='attendance',
            name='unique_enrollment_date',
        ),
        migrations.AddField(
            model_name='attendance',
            name='attendance_batch',
            field=models.CharField(choices=[('4pm - 5pm', 'Batch 4Pm 5Pm'), ('5pm - 6pm', 'Batch 5Pm 6Pm'), ('6pm - 7pm', 'Batch 6Pm 7Pm'), ('7pm - 8pm', 'Batch 7Pm 8Pm'), ('11am - 12pm', 'Batch 11Am 12Pm'), ('12pm - 1pm', 'Batch 12Pm 1Pm'), ('1pm - 2pm', 'Batch 1Pm 2Pm'), ('2pm - 3pm', 'Batch 2Pm 3Pm')], default='5pm - 6pm', max_length=20),
        ),
        migrations.AddConstraint(
            model_name='attendance',
            constraint=models.UniqueConstraint(fields=('enrollment', 'attendance_date', 'attendance_batch'), name='unique_enrollment_date_batch'),
        ),
        migrations.RemoveField(
            model_name='attendance',
            name='remarks',
        ),
        migrations.RemoveField(
            model_name='attendance',
            name='updated_at',
        ),
    ]
